### PR TITLE
Webpage in master 2

### PR DESCRIPTION
**Pull request by stereobooster**
Readme generated from `data.json`

### CODE REVIEW

**Comment by stereobooster** [comment]
@MicheleBertoli I rebased this branch. Now data.json is source of truth and you can generate Readme based on it. WDYT?

**Comment by MicheleBertoli** [comment]
Thank you very much, @stereobooster.
I like the idea of the `data.json`, and I'm happy to merge this.
It'd be great if we could centre the tick inside the cell - do you think it's feasible?
Also, nit: I don't really like the if/else-if on the headers - do you mind using an object?

**Comment by stereobooster** [comment]
Easy. WIll fix tomorrow

**Comment by stereobooster** [comment]
Here is how centered ticks looks like. If you ask me this is strange

screen shot 2018-01-23 at 11 03 46

**Comment by stereobooster** [comment]
We can use [pad option](https://github.com/wooorm/markdown-table#optionspad) to make markdown table more compact.

**Comment by MicheleBertoli** [comment]
Thanks for improving it but I agree it doesn't look right.
Ideally, it should look like the current README (alternate row colours, column border, etc.).
Do you think it's possible with [markdown-table](https://github.com/wooorm/markdown-table)?

**Comment by stereobooster** [comment]
Not sure I understand what you want.

Current version (1):

```markdown
| [aphrodite](https://github.com/Khan/aphrodite) | 1.2.3        | ✓                          | ✓              | ✓             | ✓                         | ✓                |
```

I can do this instead (2):

```markdown
| [aphrodite](https://github.com/Khan/aphrodite) | 1.2.3 | ✓ | ✓ | ✓ | ✓ | ✓ |
```

**Comment by stereobooster** [comment]
> Ideally, it should look like the current README (alternate row colours, column border, etc.).

If you are talking about tweaking styles for table in html version. I agree, but this is out of scope of current PR. This PR about generating `README` from `data.json`

**Comment by MicheleBertoli** [comment]
I was always talking about the README, especially when I said:
> It'd be great if we could centre the tick inside the cell - do you think it's feasible?

It seems there's a been a misunderstanding and you centered the ticks on the website (which, I agree, is out of the scope of this PR) instead of doing it in the [README](https://github.com/stereobooster/css-in-js/blob/588acce900c92decdceac5c4db0fe34c2c57e60a/README.md).
I also thought your screenshot showed the README (therefore my comment).

So, it'd be great if we could centre the tick inside the cell **of the README** - and leave the website as it is now.
Does that make sense?
Thank you very much!

**Comment by stereobooster** [comment]
Done. Check a diff of the README

**Comment by stereobooster** [comment]
This is how it looks https://github.com/stereobooster/css-in-js/tree/webpage-in-master-2

**Comment by MicheleBertoli** [comment]
Yay, thank you very much!

**Pull request merged**
