### PR TITLE
Update name and url of cxs

### PR DESCRIPTION
**Pull request by JayAndCatchFire**
`react-cxs` has moved to another repository and changed its name to `cxs`.

### CODE REVIEW

**Comment by stereobooster** [comment]
Hi. Thank you for contribution. Can you, please, update contents of `css-in-js/react-cxs` (rename folder and update code)?

**Comment by JayAndCatchFire** [comment]
Sure thing!  I forgot about that.

**Comment by JayAndCatchFire** [comment]
@stereobooster Everything should be up to date now.

**Comment by JayAndCatchFire** [comment]
Also, here's a thing.  I don't know if this is the right place for this discussion, but here goes.

I'm not completely sure that cxs qualifies for the "Extract CSS File" checkmark anymore.  I mean, it supports extracting the CSS using a function that returns a string.  It supports SSR.  But I don't see any official support for extracting a CSS _file_.

Thoughts?  Feelings?

**Comment by MicheleBertoli** [comment]
Thank you very much, @JayAndCatchFire @stereobooster.
Although there's no official support for extracting the CSS, it can be done by saving the output `cxs.css()` into a separate file.

**Pull request merged**
