### PR TITLE
update version for aphrodite

### PR DESCRIPTION
**Pull request by hozefaj**
Updated version in aphrodite per https://github.com/Khan/aphrodite/blob/master/package.json#L3

### CODE REVIEW

**Comment by kwelch** [comment]
The version number relates directly to the version used in the example. Could you also update the example to match any updates required for that version.

**Comment by hozefaj** [comment]
Sure will do.

**Comment by hozefaj** [comment]
I checked the docs for `aphrodite` v1.2.3 and the core API has not changed used in the example code. Checked it locally and its working as expected. No update on the code is needed.

**Comment by MicheleBertoli** [comment]
Thank you very much @hozefaj @kwelch 
I appreciate the APIs are not changed but It'd be awesome if you could update the version in the `package.json` of the example as well.

**Comment by hozefaj** [comment]
@MicheleBertoli Oops..my bad...let me do that 👍

**Comment by MicheleBertoli** [comment]
🙌

**Pull request merged**
