### PR TITLE
[added] react-inline

### PR DESCRIPTION
**Pull request by martinandert**
See https://github.com/martinandert/react-inline

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thank you very much @martinandert, amazing job!
If you don't mind, I would ask you to use the same style I used for all the demos.
I understand that you wanted to show all the features of your lib but I would prefer to be "consistent" between the projects at the moment.
If you need help, please ask :)

**Comment by martinandert** [comment]
No problem, will fix it.

**Comment by martinandert** [comment]
Done.

**Comment by MicheleBertoli** [comment]
Great, thanks! :+1:

**Pull request merged**
