### PR TITLE
Update aphrodite

### PR DESCRIPTION
**Pull request by kentcdodds**
Aphrodite supports server side rendering which means generating a CSS file is trivial. Also, it does autoprefixing.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Hello @kentcdodds, thank you very much for your PR!

I'm sorry for the missing features but when I added the library to the repo (v0.1.2), the `autoprefixing` wasn't published yet.
It would be great if you could also upgrade the library on the example and the version on the readme.

"Extract CSS File" means being able to export a plain CSS file at build time (that can be pushed on a CDN, for example) and, as far as I understand, `aphrodite` doesn't support that. 
It is obviously possible to generate a file using `renderStatic` but that's different.
Am I wrong?

**Comment by kentcdodds** [comment]
Hi @MicheleBertoli!
I'll be happy to update the example as well.

As for "Extract CSS File" it may be a little loosy-goosy. It's totally possible to do and it's straightforward. It just takes a little work on the part of the developer. It pretty much amounts to a simple call like this:

```javascript
const {css} = StyleSheetServer.renderStatic(() => {
  // do all your aphrodite.css calls in this callback
  // In a universal react app, this would be something like:
  // ReactDOMServer.renderToStaticMarkup(<Root />)
  // and all the `css` calls would be in the `render` method
})
fs.writeFileSync('./path/to.css', css.content)
```

For an example, the [JavaScriptAir.com](https://javascriptair.com) website does [this](https://github.com/javascriptair/site/blob/a9c57cf4dcd81d5fc49781b6bccc6e009bb198bd/generate/renderComponentToFile.js#L7-L13) to generate all of its pages (resulting in a 100% static site with basically 0 JS shipped to the browser).

**Comment by kentcdodds** [comment]
I've updated my PR to update all dependencies and added a script that will generate a css file (just for demonstration purposes).

**Comment by MicheleBertoli** [comment]
Awesome @kentcdodds, thanks!

**Pull request merged**
