### PR TITLE
Updating versions in table by adding badges

### PR DESCRIPTION
**Pull request by davidkpiano**
This PR adds badges from badge.fury.io to always show the most recent version number of the packages on the table.

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thank you very much @davidkpiano, I appreciate your contribution.

However, I can't merge your PR because we don't want the version number on the table to be the most recent one.
We want it to be the version that we tried and the version that reflects the features listed in the table itself.

If the version number is always the most recent one and the features are related to a previous version, the table becomes inconsistent.

**Comment by rofrischmann** [comment]
How about adding another column? Would kinda reflect the up-to-date the tested version is.

**Comment by davidkpiano** [comment]
> How about adding another column? Would kinda reflect the up-to-date the tested version is.

I agree; people are coming here to compare CSS-in-JS techniques of packages that are being used today, or that they will likely install and use. They're not going to install the exact version on the table; they're going to install the latest version. So either way, the table is a little misleading.

**Comment by MicheleBertoli** [comment]
Adding a new column with the current version (or, better, adding the current version beside the package name) seems like a good idea, thanks @rofrischmann.
It will also help people (myself included) figure out which packages need to be updated and, hopefully, submit a PR.

Something like would work:
screen shot 2016-10-15 at 07 27 38

@davidkpiano I agree that keeping the table up-to-date with the latest versions and the latest features would be the ideal solution. Sometimes I do that, sometimes package owners do that.
Feel free to help if you have time.

**Pull request closed without merging**
