### PR TITLE
ADD: cssobj project demo

### PR DESCRIPTION
**Pull request by futurist**
Please see demo for this commit:

https://cssobj.github.io/cssobj-demo/button/

Repo: [cssobj](https://github.com/cssobj/cssobj) - [demo](https://cssobj.github.io/cssobj-demo/)

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
hey @futurist, thanks for your PR and your library.
I would only ask you to make the example consistent with all the others (e.g. remove reflection, onClick handler, etc.) and then we can merge.

**Comment by futurist** [comment]
Thanks for the review @MicheleBertoli , should also remove the `textarea` for display result css?

**Comment by MicheleBertoli** [comment]
thanks @futurist 
I understand its potential and how it's useful but I believe consistency between demos is one of the most important aspects, so I would remove it.

**Comment by futurist** [comment]
Please check the new commit

**Comment by MicheleBertoli** [comment]
Awesome. thanks!
I'm going to merge it and it to the README.

**Pull request merged**
