### PR TITLE
feat: updated Styled Components to latest

### PR DESCRIPTION
**Pull request by postrad**
Updating Styled Components to current release, and updating React as well. I also updated the code sample to reflect the latest syntax.

### CODE REVIEW

**Comment by postrad** [comment]
@streamich good point- `package-lock.json` removed.

**Comment by MicheleBertoli** [comment]
This is awesome, thank you very much @postrad for updating the package and @streamich for reviewing the PR.
I would just ask @postrad to update the version in the table as well before merging.

**Comment by stereobooster** [comment]
> Re-generate the table with: cd webpage && yarn && yarn readme

**Comment by postrad** [comment]
Updated the version in the table. 😃

**Comment by MicheleBertoli** [comment]
🙌 Thank you very much @postrad.

**Comment by stereobooster** [comment]
but Readme is not updated

**Comment by MicheleBertoli** [comment]
Oops I trusted the commit name : )
I pushed a fix.
Thank you very much @stereobooster.

**Comment by postrad** [comment]
@MicheleBertoli I’m sorry about that- I thought I ran the `yarn` task successfully but instead I see I just removed the `yarn.lock` file. I will make sure my future PRs aren’t so troublesome! And thanks @stereobooster for your help.

**Pull request merged**
