### PR TITLE
A bit of header tags

### PR DESCRIPTION
**Pull request by stereobooster**
Before I will jump into serious stuff

### CODE REVIEW

**Comment by MicheleBertoli** [comment]
Thank you very much, @stereobooster.
This is pretty cool stuff and I'm happy to merge it.

The only thing I'd change is the image: I don't think the message of this repo is "I'm confused about the CSSinJS libraries" but a more positive "hey, look how many smart solutions have been created".
I hope this makes sense for you.
Would you mind changing/removing the picture?

**Comment by stereobooster** [comment]
> Would you mind changing/removing the picture?

Yes of course. Will remove it till we come up with better one.

**Comment by MicheleBertoli** [comment]
Also, would you like to be added to the collaborators of this project?
It's still great to review each others code but you'd be able to create branches in this repo, manage issues, etc.
Thank you very much!

**Comment by stereobooster** [comment]
Yes, it would be nice. 

I still would like to get reviews about my PRs.

**Comment by MicheleBertoli** [comment]
Oh yes, sure - same applies to my PRs.
I'm a big fan of code reviews.

I added you, thank you very much one more time for helping out with the repo.

**Comment by stereobooster** [comment]
Image fixed. I tested it.

**Comment by MicheleBertoli** [comment]
🙌

**Pull request merged**
